import {createServerFn} from "@tanstack/react-start";
import {z} from "zod";
import {createHash} from "node:crypto";
import {requireSupabaseAuth} from "@/integrations/supabase/auth-middleware";
import {supabaseAdmin} from "@/integrations/supabase/client.server";
import {voiceProvider,musicProvider} from "./audio.providers.server";
const db:any=supabaseAdmin;
async function url(path:string){const {data,error}=await db.storage.from("project-assets").createSignedUrl(path,900);if(error)throw new Error("Playback URL unavailable");return data.signedUrl}
async function job(s:any,slug:string,projectId:string,input:any){const r=await s.rpc("start_generation_job",{_task_slug:slug,_project_id:projectId,_input:input});if(r.error||!r.data)throw new Error(r.error?.message||"Couldn't start generation");return r.data as string}
async function failJob(id:string,msg:string){await db.rpc("fail_generation_job",{_job_id:id,_error:msg})}
async function doneJob(id:string,out:any){await db.rpc("complete_generation_job",{_job_id:id,_output:out})}

export const generateSceneVoiceover=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(d=>z.object({projectId:z.string().uuid(),sceneId:z.string().uuid(),voiceId:z.string().uuid(),instructions:z.string().max(500).optional(),speed:z.number().min(.25).max(4).optional()}).parse(d)).handler(async({data,context})=>{
 const s:any=context.supabase; const scene=(await s.from("scenes").select("id,title,narration").eq("id",data.sceneId).eq("project_id",data.projectId).maybeSingle()).data;
 if(!scene)return{ok:false,error:"Scene not found."}; if(!scene.narration?.trim())return{ok:false,error:"Add narration first."};
 const voice=(await s.from("voices").select("id,provider,provider_voice_id,name").eq("id",data.voiceId).maybeSingle()).data;if(!voice)return{ok:false,error:"Voice not found."};
 let id:string;try{id=await job(s,"tts_voiceover",data.projectId,{sceneId:data.sceneId,voiceId:data.voiceId})}catch(e:any){return{ok:false,error:e.message.includes("INSUFFICIENT_CREDITS")?"Not enough credits.":"Couldn't start voiceover job."}}
 try{const p=voiceProvider(voice.provider);const audio=await p.synthesize({text:scene.narration,voiceId:voice.provider_voice_id,instructions:data.instructions,speed:data.speed});
  const hash=createHash("sha256").update(scene.narration).digest("hex"),path=`${context.userId}/${data.projectId}/audio/voiceovers/${crypto.randomUUID()}.mp3`;
  const up=await db.storage.from("project-assets").upload(path,audio.bytes,{contentType:audio.contentType});if(up.error)throw new Error("Couldn't store voiceover");
  const a=(await db.from("assets").insert({project_id:data.projectId,scene_id:data.sceneId,kind:"voice",name:`${scene.title} — ${voice.name}`,storage_path:path,meta:{provider:voice.provider,model:voice.provider==="openai"?"gpt-4o-mini-tts":"eleven_v3",text_hash:hash}}).select("id").single()).data;
  if(!a)throw new Error("Couldn't register voiceover asset");
  const v=(await db.from("voiceovers").insert({project_id:data.projectId,scene_id:data.sceneId,voice_id:data.voiceId,generation_job_id:id,asset_id:a.id,provider:voice.provider,model:voice.provider==="openai"?"gpt-4o-mini-tts":"eleven_v3",text:scene.narration,text_hash:hash,status:"ready"}).select("id").single()).data;if(!v)throw new Error("Couldn't register voiceover");
  await db.from("scene_audio").upsert({project_id:data.projectId,scene_id:data.sceneId,voiceover_id:v.id,updated_at:new Date().toISOString()},{onConflict:"scene_id"});await doneJob(id,{voiceoverId:v.id,assetId:a.id,path});return{ok:true,url:await url(path),voiceoverId:v.id}
 }catch(e:any){await failJob(id,e.message);return{ok:false,error:e.message+" Your credits were refunded."}}
});

export const previewVoice=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(d=>z.object({projectId:z.string().uuid(),voiceId:z.string().uuid()}).parse(d)).handler(async({data,context})=>{
 const s:any=context.supabase;const v=(await s.from("voices").select("provider,provider_voice_id,preview_url").eq("id",data.voiceId).maybeSingle()).data;if(!v)return{ok:false,error:"Voice not found."};if(v.preview_url)return{ok:true,url:v.preview_url,charged:false};
 let id:string;try{id=await job(s,"tts_preview",data.projectId,{voiceId:data.voiceId})}catch(e:any){return{ok:false,error:"Couldn't start preview."}}
 try{const a=await voiceProvider(v.provider).synthesize({text:"This is a short preview for your video.",voiceId:v.provider_voice_id});const path=`${context.userId}/${data.projectId}/audio/previews/${data.voiceId}.mp3`;const up=await db.storage.from("project-assets").upload(path,a.bytes,{contentType:a.contentType,upsert:true});if(up.error)throw new Error("Couldn't store preview");await doneJob(id,{preview:true,path});return{ok:true,url:await url(path),charged:true}}catch(e:any){await failJob(id,e.message);return{ok:false,error:e.message+" Your credits were refunded."}}
});

export const syncElevenLabsVoices=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).handler(async()=>{
 const p=voiceProvider("elevenlabs");if(!p.listVoices)return{ok:false,error:"Voice listing unavailable"};const rows=await p.listVoices();if(rows.length){const {error}=await db.from("voices").upsert(rows.map((v:any)=>({provider:"elevenlabs",provider_voice_id:v.providerVoiceId,name:v.name,language:v.language,accent:v.accent,style:v.style,category:v.category,gender:v.gender,preview_url:v.previewUrl,status:"active",metadata:v.metadata||{},updated_at:new Date().toISOString()})),{onConflict:"provider,provider_voice_id"});if(error)throw error}return{ok:true,count:rows.length}
});

export const cloneVoice=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(d=>z.object({projectId:z.string().uuid(),assetId:z.string().uuid(),name:z.string().min(2).max(100),description:z.string().max(500).optional(),consentConfirmed:z.literal(true)}).parse(d)).handler(async({data,context})=>{
 const s:any=context.supabase;const a=(await s.from("assets").select("id,storage_path,name,meta").eq("id",data.assetId).eq("project_id",data.projectId).maybeSingle()).data;if(!a?.storage_path)return{ok:false,error:"Voice sample not found."};let id:string;try{id=await job(s,"clone_voice",data.projectId,{assetId:data.assetId,consentConfirmed:true})}catch(e:any){return{ok:false,error:"Couldn't start cloning."}}
 try{const file=await db.storage.from("project-assets").download(a.storage_path);if(file.error)throw new Error("Couldn't read sample");const bytes=Buffer.from(await file.data.arrayBuffer());const r=await voiceProvider("elevenlabs").clone!({name:data.name,description:data.description,file:bytes,filename:a.name,contentType:a.meta?.type||"audio/mpeg"});const c=(await db.from("voice_clones").insert({user_id:context.userId,project_id:data.projectId,source_asset_id:data.assetId,provider:"elevenlabs",provider_voice_id:r.voiceId,name:data.name,consent_confirmed:true,consent_text:"I confirm I have authorization to clone this speaker's voice.",status:r.requiresVerification?"processing":"ready"}).select("id").single()).data;if(!c)throw new Error("Couldn't save clone");await db.from("voices").upsert({provider:"elevenlabs",provider_voice_id:r.voiceId,name:data.name,language:"en",category:"cloned",status:"active",metadata:{clone_id:c.id}},{onConflict:"provider,provider_voice_id"});await doneJob(id,{cloneId:c.id,voiceId:r.voiceId});return{ok:true,cloneId:c.id,voiceId:r.voiceId}}catch(e:any){await failJob(id,e.message);return{ok:false,error:e.message+" Your credits were refunded."}}
});

export const generateMusicTrack=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(d=>z.object({projectId:z.string().uuid(),title:z.string().min(1).max(120),prompt:z.string().min(10).max(1000),durationSeconds:z.number().int().min(3).max(600),genre:z.string().max(80).optional(),mood:z.string().max(80).optional()}).parse(d)).handler(async({data,context})=>{
 const s:any=context.supabase;let id:string;try{id=await job(s,"generate_music",data.projectId,{prompt:data.prompt,durationSeconds:data.durationSeconds})}catch(e:any){return{ok:false,error:"Couldn't start music generation."}}
 try{const a=await musicProvider().compose({prompt:data.prompt,durationMs:data.durationSeconds*1000});const path=`${context.userId}/${data.projectId}/audio/music/${crypto.randomUUID()}.mp3`;const up=await db.storage.from("project-assets").upload(path,a.bytes,{contentType:a.contentType});if(up.error)throw new Error("Couldn't store music");const asset=(await db.from("assets").insert({project_id:data.projectId,kind:"music",name:data.title,storage_path:path,meta:{provider:"elevenlabs",provider_asset_id:a.providerAssetId}}).select("id").single()).data;if(!asset)throw new Error("Couldn't register music asset");const track=(await db.from("music_tracks").insert({project_id:data.projectId,asset_id:asset.id,title:data.title,genre:data.genre,mood:data.mood,duration_seconds:data.durationSeconds,license:"provider-generated",provider:"elevenlabs",provider_asset_id:a.providerAssetId,attribution:"Generated with ElevenLabs Music API"}).select("id").single()).data;await doneJob(id,{trackId:track?.id,assetId:asset.id,path});return{ok:true,trackId:track?.id,url:await url(path)}}catch(e:any){await failJob(id,e.message);return{ok:false,error:e.message+" Your credits were refunded."}}
});
