import {useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {useServerFn} from "@tanstack/react-start";
import {AudioLines,Loader2,Play,RefreshCw,Sparkles,Music2,SlidersHorizontal} from "lucide-react";
import {toast} from "sonner";
import {supabase} from "@/integrations/supabase/client";
import {generateSceneVoiceover,previewVoice,syncElevenLabsVoices,generateMusicTrack} from "@/lib/audio.functions";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import type {Tables} from "@/integrations/supabase/types";
const db:any=supabase;
export function AudioPanel({project}:{project:Tables<"projects">}){
 const qc=useQueryClient();const sync=useServerFn(syncElevenLabsVoices);const music=useServerFn(generateMusicTrack);
 const {data:scenes=[]}=useQuery({queryKey:["scenes",project.id],queryFn:async()=>{const r=await db.from("scenes").select("*").eq("project_id",project.id).order("position");if(r.error)throw r.error;return r.data||[]}});
 const {data:voices=[]}=useQuery({queryKey:["voices"],queryFn:async()=>{const r=await db.from("voices").select("*").eq("status","active").order("name");if(r.error)throw r.error;return r.data||[]}});
 const {data:tracks=[]}=useQuery({queryKey:["music_tracks",project.id],queryFn:async()=>{const r=await db.from("music_tracks").select("*").eq("project_id",project.id).order("created_at",{ascending:false});return r.data||[]}});
 const [syncing,setSyncing]=useState(false);
 async function refresh(){await Promise.all([qc.invalidateQueries({queryKey:["scenes",project.id]}),qc.invalidateQueries({queryKey:["voices"]}),qc.invalidateQueries({queryKey:["music_tracks",project.id]}),qc.invalidateQueries({queryKey:["scene_audio",project.id]}),qc.invalidateQueries({queryKey:["profile"]})])}
 return <div className="space-y-6">
  <div className="rounded-2xl border border-border bg-surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono text-xs text-signal">AUDIO STUDIO</p><h2 className="text-2xl font-semibold">Voice, music & mix</h2><p className="text-sm text-muted-foreground">Generate narration per scene and prepare audio assignments for the timeline.</p></div><Button variant="panel" size="sm" disabled={syncing} onClick={async()=>{setSyncing(true);try{const r=await sync();if(!r.ok)toast.error(r.error);else toast.success(`Synced ${r.count} ElevenLabs voices`);await refresh()}catch(e:any){toast.error(e.message)}finally{setSyncing(false)}}}>{syncing?<Loader2 className="animate-spin"/>:<RefreshCw/>} Sync ElevenLabs</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Stat n={voices.length} l="Voices"/><Stat n={scenes.length} l="Scenes"/><Stat n={tracks.length} l="Music beds"/></div></div>
  <MusicComposer project={project} tracks={tracks} generate={music} refresh={refresh}/>
  <div><div className="mb-3 flex items-center gap-2"><AudioLines className="size-4 text-signal"/><div><p className="font-mono text-xs text-muted-foreground">SCENE NARRATION</p><p className="text-xs text-muted-foreground">Voice generation is charged through the existing server-side credit ledger.</p></div></div><div className="space-y-3">{scenes.map((s:any,i:number)=><SceneAudio key={s.id} scene={s} index={i} project={project} voices={voices} refresh={refresh}/>)}</div></div>
 </div>
}
function Stat({n,l}:{n:number;l:string}){return <div className="rounded-xl border border-border bg-surface-raised p-3"><p className="font-mono text-[10px] uppercase text-muted-foreground">{l}</p><p className="text-xl font-semibold">{n}</p></div>}
function SceneAudio({scene,index,project,voices,refresh}:{scene:any;index:number;project:any;voices:any[];refresh:()=>Promise<void>}){
 const gen=useServerFn(generateSceneVoiceover),preview=useServerFn(previewVoice);const [voice,setVoice]=useState(voices[0]?.id||"");const [busy,setBusy]=useState("");const [url,setUrl]=useState("");
 async function run(kind:"generate"|"preview"){setBusy(kind);try{const fn=kind==="generate"?gen:preview;const r=kind==="generate"?await fn({data:{projectId:project.id,sceneId:scene.id,voiceId:voice}}):await fn({data:{projectId:project.id,voiceId:voice}});if(!r.ok)toast.error(r.error);else{setUrl(r.url);toast.success(kind==="generate"?"Voiceover ready":"Preview ready");await refresh()}}catch(e:any){toast.error(e.message)}finally{setBusy("")}}
 async function saveMix(e:React.ChangeEvent<HTMLInputElement>){const value=Number(e.target.value);await db.from("scene_audio").upsert({project_id:project.id,scene_id:scene.id,voice_volume:value,updated_at:new Date().toISOString()},{onConflict:"scene_id"});toast.success("Mix saved")}
 return <div className="rounded-xl border border-border bg-surface p-4"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs text-signal">{String(index+1).padStart(2,"0")}</span><div className="min-w-40 flex-1"><p className="font-semibold">{scene.title}</p><p className="line-clamp-1 text-xs text-muted-foreground">{scene.narration||"No narration"}</p></div><select value={voice} onChange={e=>setVoice(e.target.value)} className="h-9 rounded-md border border-border bg-surface px-2 text-sm">{voices.map(v=><option key={v.id} value={v.id}>{v.name} · {v.provider}</option>)}</select><Button size="sm" variant="panel" disabled={!voice||!!busy} onClick={()=>run("preview")}>{busy==="preview"?<Loader2 className="animate-spin"/>:<Play/>} Preview</Button><Button size="sm" variant="signal" disabled={!voice||!scene.narration||!!busy} onClick={()=>run("generate")}>{busy==="generate"?<Loader2 className="animate-spin"/>:<Sparkles/>} Generate</Button></div>{url&&<audio className="mt-3 w-full" controls src={url}/>}<div className="mt-3 grid gap-3 rounded-lg border border-border p-3 sm:grid-cols-2"><label className="text-xs text-muted-foreground"><span className="flex justify-between"><span>Voice volume</span><span>100%</span></span><input className="mt-2 w-full" type="range" min="0" max="2" step=".05" defaultValue="1" onChange={saveMix}/></label><div className="flex items-center gap-2 text-xs text-muted-foreground"><SlidersHorizontal className="size-4 text-signal"/>Ducking defaults on; attack/release are stored in scene_audio for Timeline.</div></div></div>
}
function MusicComposer({project,tracks,generate,refresh}:{project:any;tracks:any[];generate:any;refresh:()=>Promise<void>}){
 const [title,setTitle]=useState("Cinematic bed"),[prompt,setPrompt]=useState("Atmospheric cinematic instrumental with subtle tension, warm strings and restrained percussion, no vocals"),[seconds,setSeconds]=useState(30),[busy,setBusy]=useState(false);
 return <section className="rounded-2xl border border-border bg-surface p-5"><div className="flex items-center gap-2"><Music2 className="size-4 text-signal"/><div><p className="font-mono text-xs text-muted-foreground">MUSIC LIBRARY</p><h3 className="font-semibold">Generate an instrumental bed</h3></div></div><div className="mt-3 grid gap-2 md:grid-cols-[180px_1fr_90px_auto]"><Input value={title} onChange={e=>setTitle(e.target.value)}/><Input value={prompt} onChange={e=>setPrompt(e.target.value)}/><Input type="number" min={3} max={600} value={seconds} onChange={e=>setSeconds(Number(e.target.value)||3)}/><Button variant="signal" disabled={busy||prompt.length<10} onClick={async()=>{setBusy(true);try{const r=await generate({data:{projectId:project.id,title,prompt,durationSeconds:seconds}});if(!r.ok)toast.error(r.error);else toast.success("Music added");await refresh()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}>{busy?<Loader2 className="animate-spin"/>:<Sparkles/>} Generate</Button></div>{tracks.length>0&&<div className="mt-3 grid gap-2 md:grid-cols-2">{tracks.map(t=><div key={t.id} className="rounded-lg border border-border p-3"><p className="text-sm font-medium">{t.title}</p><p className="text-[10px] uppercase text-muted-foreground">{t.provider} · {t.license}</p></div>)}</div>}</section>
}
