import {useEffect,useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {useServerFn} from "@tanstack/react-start";
import {Download,Loader2,Play,RefreshCw,Square,Video,AlertCircle,CheckCircle2,Clock3} from "lucide-react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {supabase} from "@/integrations/supabase/client";
import {createRenderJob,getRenderJob,cancelRenderJob,getExportUrl} from "@/lib/render.functions";
import type {Tables} from "@/integrations/supabase/types";
const db:any=supabase;
export function RenderPanel({project}:{project:Tables<"projects">}){
 const qc=useQueryClient();const create=useServerFn(createRenderJob),poll=useServerFn(getRenderJob),cancel=useServerFn(cancelRenderJob),download=useServerFn(getExportUrl);
 const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<string|null>(null);
 const {data:jobs=[]}=useQuery({queryKey:["render_jobs",project.id],queryFn:async()=>{const r=await db.from("render_jobs").select("*").eq("project_id",project.id).order("created_at",{ascending:false}).limit(10);if(r.error)throw r.error;return r.data||[]}});
 const {data:exports=[]}=useQuery({queryKey:["exports",project.id],queryFn:async()=>{const r=await db.from("exports").select("*").eq("project_id",project.id).order("created_at",{ascending:false}).limit(10);if(r.error)throw r.error;return r.data||[]}});
 const active=jobs.find((j:any)=>j.status==="queued"||j.status==="processing");
 useEffect(()=>{if(!active)return;const id=window.setInterval(async()=>{const r=await poll({data:{projectId:project.id,jobId:active.id}});if(r.ok){qc.invalidateQueries({queryKey:["render_jobs",project.id]});qc.invalidateQueries({queryKey:["exports",project.id]});if(r.job?.status==="completed")toast.success("Render completed");if(r.job?.status==="failed")toast.error(r.job.error||"Render failed")}},5000);return()=>window.clearInterval(id)},[active?.id,project.id]);
 async function start(){setBusy(true);try{const r=await create({data:{projectId:project.id}});if(!r.ok)toast.error(r.error);else{toast.success(r.dispatched?"Render dispatched":"Render queued");setSelected(r.jobId);await refresh()}}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function stop(id:string){const r=await cancel({data:{projectId:project.id,jobId:id}});if(!r.ok)toast.error(r.error);else{toast.success("Render cancelled");refresh()}}
 async function openExport(id:string){const r=await download({data:{projectId:project.id,exportId:id}});if(!r.ok)toast.error(r.error);else window.open(r.url,"_blank")}
 async function refresh(){await Promise.all([qc.invalidateQueries({queryKey:["render_jobs",project.id]}),qc.invalidateQueries({queryKey:["exports",project.id]})])}
 const latest=selected?jobs.find((j:any)=>j.id===selected):jobs[0];
 return <div className="space-y-5">
  <section className="rounded-2xl border border-border bg-surface p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-xs text-signal">RENDER ENGINE</p><h2 className="text-2xl font-semibold">Render & export</h2><p className="text-sm text-muted-foreground">Create an immutable render manifest from the current timeline and dispatch it to the configured renderer.</p></div><div className="flex gap-2"><Button size="sm" variant="panel" onClick={refresh}><RefreshCw/> Refresh</Button><Button size="sm" variant="signal" disabled={busy||!!active} onClick={start}>{busy?<Loader2 className="animate-spin"/>:<Play/>} Render video</Button></div></div>
   {latest&&<div className="mt-5 rounded-xl border border-border bg-surface-raised p-4"><div className="flex items-center gap-3"><StatusIcon status={latest.status}/><div className="flex-1"><p className="text-sm font-semibold capitalize">{latest.status}</p><p className="text-xs text-muted-foreground">{latest.status==="queued"?"Waiting for renderer":latest.status==="processing"?"Renderer is processing the manifest":latest.error||"Render job"}</p></div>{(latest.status==="queued"||latest.status==="processing")&&<Button size="sm" variant="ghost" onClick={()=>stop(latest.id)}><Square/> Cancel</Button>}</div>{latest.status==="processing"&&<div className="mt-4"><div className="h-2 overflow-hidden rounded-full bg-border"><div className="h-full bg-signal transition-all" style={{width:`${Number(latest.progress||0)}%`}}/></div><p className="mt-1 text-right font-mono text-[10px] text-muted-foreground">{Number(latest.progress||0).toFixed(0)}%</p></div>}{latest.status==="queued"&&<div className="mt-3 rounded-lg border border-border p-3 text-xs text-muted-foreground">If no renderer is configured, the job remains queued. Set <code>RENDERER_URL</code> on the server to connect a cloud render worker.</div>}</div>}
  </section>
  <section className="rounded-2xl border border-border bg-surface p-5"><div className="flex items-center gap-2"><Video className="size-4 text-signal"/><div><p className="font-mono text-xs text-muted-foreground">EXPORTS</p><h3 className="font-semibold">Rendered videos</h3></div></div><div className="mt-4 space-y-2">{exports.length===0?<div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No completed exports yet.</div>:exports.map((e:any)=><div key={e.id} className="flex items-center gap-3 rounded-lg border border-border p-3"><CheckCircle2 className="size-4 text-signal"/><div className="flex-1"><p className="text-sm font-medium">{e.filename}</p><p className="text-xs text-muted-foreground">{e.format.toUpperCase()} · {e.size_bytes?formatBytes(e.size_bytes):"size pending"}</p></div>{e.status==="ready"?<Button size="sm" variant="signal" onClick={()=>openExport(e.id)}><Download/> Download</Button>:<Clock3 className="size-4 text-muted-foreground"/>}</div>)}</div></section>
 </div>
}
function StatusIcon({status}:{status:string}){if(status==="completed")return <CheckCircle2 className="size-5 text-signal"/>;if(status==="failed")return <AlertCircle className="size-5 text-destructive"/>;if(status==="processing")return <Loader2 className="size-5 animate-spin"/>;return <Clock3 className="size-5 text-muted-foreground"/>}
function formatBytes(n:number){if(n<1024)return n+" B";if(n<1048576)return (n/1024).toFixed(1)+" KB";if(n<1073741824)return (n/1048576).toFixed(1)+" MB";return (n/1073741824).toFixed(2)+" GB"}
